name: insdel_glm           # Name of the environment
channels:
  - conda-forge       # Preferred channel for many packages
  - defaults
dependencies:
  - python=3.11       # Python version
  - pandas            # Latest compatible version
  - pyarrow
  - transformers
  - pytorch
  - logomaker
  - imageio
  - seaborn
  - scikit-learn
